services:
  - type: web
    name: student-management
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true