services:
  - type: web
    name: student-management
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: student-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true


databases:
  - name: student-db
    plan: free
    databaseName: student_management
    user: student_user
